# Generated by Django 4.0.5 on 2022-06-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='recommend_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
